export enum JobHistoryEventType {
  JOB_CREATED = 'JOB_CREATED',
  JOB_UPDATED = 'JOB_UPDATED',
  NEW_INSURANCE_SCOPE_UPLOADED = 'NEW_INSURANCE_SCOPE_UPLOADED',
  INSURANCE_SCOPE_UPDATED = 'INSURANCE_SCOPE_UPDATED',
  STATUS_UPDATED = 'STATUS_UPDATED',
  COC_CREATED = 'COC_CREATED',
  ROUF_CREATED = 'ROUF_CREATED',
  PAYMENT_SCHEDULE_SENT = 'PAYMENT_SCHEDULE_SENT',
  PAYMENT_REMINDER_SENT = 'PAYMENT_REMINDER_SENT',
  COC_SENT = 'COC_SENT',
  ROUF_SENT = 'ROUF_SENT',
}
