export enum NUMBER_OF_INSURANCE_JOBS_PER_MONTH {
  ONE_TO_NINETEEN = '1-19',
  TWENTY_TO_FORTY_NINE = '20-49',
  FIFTY_TO_NINETY_NINE = '50-99',
  ONE_HUNDRED_TO_TWO_HUNDRED_FIFTY = '100-250',
  TWO_HUNDRED_FIFTY_ONE_TO_FIVE_HUNDRED = '251-500',
  MORE_THAN_FIVE_HUNDRED = '500+',
}
