export const PERMISSIONS = {
  COMPANY: 'company',
  COMPANY_LOCATION: 'company_location',
  COMPANY_LIST: 'company_list',
  COMPANY_OWNER: 'company_owner',
  COMPANY_ADMIN: 'company_admin',
  COMPANY_USER: 'company_user',
  COMPANY_SETTINGS: 'company_settings',
  MEASUREMENT_UNITS: 'units_of_measurement',
  USER: 'user',
  USER_LIST: 'user_list',
  USER_PROFILE: 'user_profile',
  USER_STATUS: 'user_status',
  USER_EMAIL: 'user_email',
  PASSWORD: 'password',
  FILE: 'file',
  CUSTOMER: 'customer',
  CUSTOMER_LIST: 'customer_list',
  SUPER_ADMIN_LIST: 'super_admin_list',
  SUPER_ADMIN: 'super_admin',
  DASHBOARD: 'dashboard',
  CLAIM_ITEMS: 'claim_items',
  INSURANCE_CARRIERS: 'insurance_carrier',
  TAX_RATES: 'tax_rates',
  MEMBERSHIP_BILLING: 'membership_billing',
  UOM: 'unit_of_measurement,',
  IMPORTS: 'insurance_scope',
  NOTES: 'notes',
  EMAIL_TEMPLATES: 'email_template',
  DOCUMENTS: 'documents',
  ALGORITHM_ACCURACY: 'algorithm_accuracy',
};

export const PERMISSION_ACTIONS = {
  CREATE: 'create',
  APPROVE: 'approve',
  GET: 'get',
  UPDATE: 'update',
  DELETE: 'delete',
  INVITE: 'invite',
  IMPORT: 'import',
  GET_BY_ID: 'get_by_id',
  CHANGE: 'change',
  UPLOAD: 'upload',
  SET: 'set',
  ALL: 'all',
  ADD_TO_GLOBAL: 'add_to_global',
  REJECT: 'reject',
};
