export const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  INITIAL_ADMIN: 'INITIAL_ADMIN',
  COMPANY_ADMIN: 'COMPANY_ADMIN',
  COMPANY_OWNER: 'COMPANY_OWNER',
  COMPANY_USER: 'COMPANY_USER',
};

export const CUSTOMER_ROLE = {
  BUSINESS: 'BUSINESS',
  INDIVIDUAL: 'INDIVIDUAL',
};

export const CUSTOMER_TYPE = {
  ALL: 'ALL',
  PARENT: 'PARENT',
  SUB: 'SUB',
};
