// fields name related to backend names
export const IMPORT_DETAILS_FIELDS = {
  ID: 'id',
  CLAIM_NUMBER: 'claimNumber',
  STATUS: 'status',
  TYPE_OF_LOSS: 'typeOfLoss',
  DATE_OF_LOSS: 'dateOfLoss',
  DATE_INSPECTED: 'dateInspected',
  DATE_CONTACTED: 'dateContacted',
  DATE_RECEIVED: 'dateReceived',
  DATE_ENTERED: 'dateEntered',
  POLICY_NUMBER: 'policyNumber',
  PRICE_LIST: 'priceList',
  INITIAL_DOCUMENT_ID: 'initialDocumentId',
  INITIAL_DOCUMENT_LINK: 'initialDocumentLink',
  INITIAL_DOCUMENT_NAME: 'initialDocumentName',
  TOTAL: 'total',
  TOTAL_RCV: 'totalRcv',
  TOTAL_OVERHEAD: 'totalOverhead',
  TOTAL_DEPRECIATION: 'totalDepreciation',
  DEDUCTIBLE: 'deductible',
  TOTAL_ACV: 'totalAcv',
  TOTAL_TAX: 'totalTax',
  TOTAL_LINE_ITEMS: 'totalLineItems',
  NET_CLAIM_SUM: 'netClaimSum',
  NET_CLAIM_IF_DEPRECIATION_IS_RECOVERED: 'netClaimIfDepreciationIsRecovered',
  TOTAL_RECOVERABLE_DEPRECIATION_SUM: 'totalRecoverableDepreciationSum',
  TOTAL_NON_RECOVERABLE_DEPRECIATION_SUM: 'totalNonRecoverableDepreciationSum',
  CREATED_AT: 'createdAt',
  UPDATED_AT: 'updatedAt',

  // customer
  CUSTOMER_ID: 'id',
  CUSTOMER: 'customer',
  CUSTOMER_DISPLAY_NAME: 'displayName',
  CUSTOMER_TYPE: 'type',
  CUSTOMER_FIRST_NAME: 'firstName',
  CUSTOMER_LAST_NAME: 'lastName',
  CUSTOMER_PHONE: 'phone',
  CUSTOMER_EMAIL: 'email',
  CUSTOMER_PROPERTY_ADDRESS: 'propertyAddress',
  CUSTOMER_SHIPPING_ADDRESS: 'shippingAddress',
  CUSTOMER_CREATED_AT: 'createdAt',
  CUSTOMER_UPDATED_AT: 'updatedAt',
  SAVED_CUSTOMER: 'savedCustomer',
  FORMATTED_ADDRESS: 'formattedAddress',
  CUSTOMER_BILLING_ADDRESS: 'billingAddress',

  // insuranceCarrier
  INSURANCE_CARRIER: 'insuranceCarrier',
  INSURANCE_CARRIER_ID: 'id',
  INSURANCE_CARRIER_NAME: 'name',
  INSURANCE_CARRIER_EMAIL: 'email',
  INSURANCE_CARRIER_PHONE: 'phone',
  INSURANCE_CARRIER_FAX: 'fax',
  INSURANCE_CARRIER_ADDRESS: 'address',
  INSURANCE_CARRIER_CARRIER_ID: 'insuranceCarrierId',
  INSURANCE_CARRIER_CREATED_AT: 'createdAt',
  INSURANCE_CARRIER_UPDATED_AT: 'updatedAt',
  INSURANCE_CARRIER_ADJUSTERS: 'adjusters',
  // adjuster
  INSURANCE_CARRIER_ADJUSTER_ID: 'id',
  INSURANCE_CARRIER_ADJUSTER_NAME: 'name',
  INSURANCE_CARRIER_ADJUSTER_TYPE: 'type',
  INSURANCE_CARRIER_ADJUSTER_PHONE: 'phone',
  INSURANCE_CARRIER_ADJUSTER_EMAIL: 'email',
  INSURANCE_CARRIER_ADJUSTER_ADDRESS: 'address',

  // group
  GROUPS: 'groups',
};

export const DEFAULT_IMPORT_DETAILS = {
  [IMPORT_DETAILS_FIELDS.ID]: '',
  [IMPORT_DETAILS_FIELDS.CLAIM_NUMBER]: '',
  [IMPORT_DETAILS_FIELDS.STATUS]: '',
  [IMPORT_DETAILS_FIELDS.TYPE_OF_LOSS]: null,
  [IMPORT_DETAILS_FIELDS.DATE_OF_LOSS]: null,
  [IMPORT_DETAILS_FIELDS.DATE_INSPECTED]: null,
  [IMPORT_DETAILS_FIELDS.DATE_CONTACTED]: null,
  [IMPORT_DETAILS_FIELDS.DATE_RECEIVED]: null,
  [IMPORT_DETAILS_FIELDS.DATE_ENTERED]: null,
  [IMPORT_DETAILS_FIELDS.POLICY_NUMBER]: null,
  [IMPORT_DETAILS_FIELDS.PRICE_LIST]: null,
  [IMPORT_DETAILS_FIELDS.INITIAL_DOCUMENT_ID]: '',
  [IMPORT_DETAILS_FIELDS.INITIAL_DOCUMENT_LINK]: '',
  [IMPORT_DETAILS_FIELDS.INITIAL_DOCUMENT_NAME]: '',
  [IMPORT_DETAILS_FIELDS.TOTAL]: '',
  [IMPORT_DETAILS_FIELDS.TOTAL_RCV]: '',
  [IMPORT_DETAILS_FIELDS.TOTAL_OVERHEAD]: '',
  [IMPORT_DETAILS_FIELDS.TOTAL_DEPRECIATION]: '',
  [IMPORT_DETAILS_FIELDS.DEDUCTIBLE]: '',
  [IMPORT_DETAILS_FIELDS.TOTAL_ACV]: '',
  [IMPORT_DETAILS_FIELDS.TOTAL_TAX]: '',
  [IMPORT_DETAILS_FIELDS.TOTAL_LINE_ITEMS]: '',
  [IMPORT_DETAILS_FIELDS.NET_CLAIM_SUM]: '',
  [IMPORT_DETAILS_FIELDS.NET_CLAIM_IF_DEPRECIATION_IS_RECOVERED]: '',
  [IMPORT_DETAILS_FIELDS.TOTAL_RECOVERABLE_DEPRECIATION_SUM]: '',
  [IMPORT_DETAILS_FIELDS.TOTAL_NON_RECOVERABLE_DEPRECIATION_SUM]: '',
  [IMPORT_DETAILS_FIELDS.TOTAL_DEPRECIATION]: '',
  [IMPORT_DETAILS_FIELDS.CREATED_AT]: '',
  [IMPORT_DETAILS_FIELDS.UPDATED_AT]: '',

  // customer
  [IMPORT_DETAILS_FIELDS.CUSTOMER_ID]: '',
  [IMPORT_DETAILS_FIELDS.CUSTOMER]: '',
  [IMPORT_DETAILS_FIELDS.CUSTOMER_DISPLAY_NAME]: '',
  [IMPORT_DETAILS_FIELDS.CUSTOMER_TYPE]: '',
  [IMPORT_DETAILS_FIELDS.CUSTOMER_FIRST_NAME]: '',
  [IMPORT_DETAILS_FIELDS.CUSTOMER_LAST_NAME]: '',
  [IMPORT_DETAILS_FIELDS.CUSTOMER_PHONE]: '',
  [IMPORT_DETAILS_FIELDS.CUSTOMER_EMAIL]: '',
  [IMPORT_DETAILS_FIELDS.CUSTOMER_PROPERTY_ADDRESS]: '',
  [IMPORT_DETAILS_FIELDS.CUSTOMER_SHIPPING_ADDRESS]: '',
  [IMPORT_DETAILS_FIELDS.CUSTOMER_CREATED_AT]: '',
  [IMPORT_DETAILS_FIELDS.CUSTOMER_UPDATED_AT]: '',

  // insuranceCarrier
  [IMPORT_DETAILS_FIELDS.INSURANCE_CARRIER]: '',
  [IMPORT_DETAILS_FIELDS.INSURANCE_CARRIER_ID]: '',
  [IMPORT_DETAILS_FIELDS.INSURANCE_CARRIER_NAME]: '',
  [IMPORT_DETAILS_FIELDS.INSURANCE_CARRIER_EMAIL]: '',
  [IMPORT_DETAILS_FIELDS.INSURANCE_CARRIER_PHONE]: '',
  [IMPORT_DETAILS_FIELDS.INSURANCE_CARRIER_FAX]: '',
  [IMPORT_DETAILS_FIELDS.INSURANCE_CARRIER_ADDRESS]: '',
  [IMPORT_DETAILS_FIELDS.INSURANCE_CARRIER_CARRIER_ID]: '',
  [IMPORT_DETAILS_FIELDS.INSURANCE_CARRIER_CREATED_AT]: '',
  [IMPORT_DETAILS_FIELDS.INSURANCE_CARRIER_UPDATED_AT]: '',
  [IMPORT_DETAILS_FIELDS.INSURANCE_CARRIER_ADJUSTERS]: [],
  // adjuster
  [IMPORT_DETAILS_FIELDS.INSURANCE_CARRIER_ADJUSTER_NAME]: '',
  [IMPORT_DETAILS_FIELDS.INSURANCE_CARRIER_ADJUSTER_TYPE]: '',
  [IMPORT_DETAILS_FIELDS.INSURANCE_CARRIER_ADJUSTER_PHONE]: '',
  [IMPORT_DETAILS_FIELDS.INSURANCE_CARRIER_ADJUSTER_EMAIL]: '',
  [IMPORT_DETAILS_FIELDS.INSURANCE_CARRIER_ADJUSTER_ADDRESS]: '',

  // group
  [IMPORT_DETAILS_FIELDS.GROUPS]: '',
};

export const LOCALISATION_INFO = { object: 'adjuster' };

export const SELF_VALIDATION_SCHEMA = {
  CODE: 'code',
  TYPE: 'type',
  PROPERTY: 'property',
  ID: 'id',
};

export const IMPORT_VALIDATION_FIELDS = {
  // General
  CLAIM_NUMBER_VALIDATE: 'claimNumberValidate',
  TYPE_OF_LOSS_VALIDATE: 'typeOfLossValidate',
  DATE_OF_LOSS_FORMAT_VALIDATE: 'dateOfLossFormatValidate',
  DATE_OF_LOSS_VALUE_VALIDATE: 'dateOfLossValueValidate',
  POLICY_NUMBER_VALIDATE: 'policyNumberValidate',
  PRICE_LIST_VALIDATE: 'priceListValidate',

  //Customer
  CUSTOMER_DISPLAY_NAME_VALIDATE: 'customerDisplayNameValidate',
  CUSTOMER_NAME_VALIDATE: 'customerNameValidate',
  CUSTOMER_EMAIL_VALIDATE: 'customerEmailValidate',
  CUSTOMER_PHONE_NUMBER_VALIDATE: 'customerPhoneNumberValidate',
  CUSTOMER_PROPERTY_ADDRESS_VALIDATE: 'customerPropertyAddressValidate',
  CUSTOMER_SHIPPING_ADDRESS_VALIDATE: 'customerShippingAddressValidate',

  // Insurance carrier
  INSURANCE_CARRIER_NAME_VALIDATE: 'insuranceCarrierNameValidate',
  INSURANCE_CARRIER_EMAIL_VALIDATE: 'insuranceCarrierEmailValidate',
  INSURANCE_CARRIER_PHONE_NUMBER_VALIDATE:
    'insuranceCarrierPhoneNumberValidate',
  INSURANCE_CARRIER_FAX_VALIDATE: 'insuranceCarrierFaxValidate',
  INSURANCE_CARRIER_ADDRESS_VALIDATE: 'insuranceCarrierAddressValidate',
  INSURANCE_CARRIER_ADJUSTERS_NAME_VALIDATE:
    'insuranceCarrierAdjustersNameValidate',
  INSURANCE_CARRIER_ADJUSTERS_PHONE_VALIDATE:
    'insuranceCarrierAdjustersPhoneValidate',

  // Groups
  GROUP_NAME_VALIDATE: 'groupNameValidate',
  GROUP_NOTE_VALIDATE: 'groupNoteValidate',

  //Line items
  LINE_ITEM_DESCRIPTION_VALIDATE: 'lineItemDescriptionValidate',
  LINE_ITEM_NOTES_VALIDATE: 'lineItemNotesValidate',
  LINE_ITEM_QUANTITY_VALIDATE: 'lineItemQuantityValidate',
  LINE_ITEM_UNIT_PRICE_VALIDATE: 'lineItemUnitPriceValidate',
  LINE_ITEM_TAX_VALIDATE: 'lineItemTaxValidate',
  LINE_ITEM_OVERHEAD_VALIDATE: 'lineItemOverheadValidate',
  LINE_ITEM_RCV_VALIDATE: 'lineItemRcvValidate',
  LINE_ITEM_ACV_VALIDATE: 'lineItemAcvValidate',
  LINE_ITEM_DEPRECIATION_SUM_VALIDATE: 'lineItemDepreciationSumValidate',
  LINE_ITEM_DEPRECIATION_PERCENT_VALIDATE:
    'lineItemDepreciationPercentValidate',

  // Group totals
  GROUP_TOTAL_TAX_VALIDATE: 'groupTotalTaxValidate',
  GROUP_TOTAL_RCV_VALIDATE: 'groupTotalRcvValidate',
  GROUP_TOTAL_OVERHEAD_VALIDATE: 'groupTotalOverheadValidate',
  GROUP_TOTAL_ACV_VALIDATE: 'groupTotalAcvValidate',
  GROUP_TOTAL_DEPRECIATION_SUM_VALIDATE: 'groupTotalDepreciationSumValidate',

  // Totals
  LINE_ITEMS_TOTAL_VALIDATE: 'lineItemsTotalValidate',
  TOTAL_TAX_VALIDATE: 'totalTaxValidate',
  TOTAL_RCV_VALIDATE: 'totalRcvValidate',
  TOTAL_DEPRECIATION_SUM_VALIDATE: 'totalDepreciationSumValidate',
  DEDUCTIBLE_VALIDATE: 'deductibleValidate',
  TOTAL_ACV_VALIDATE: 'totalAcvValidate',
  TOTAL_OVERHEAD_VALIDATE: 'totalOverheadValidate',
  NET_CLAIM_SUM_VALIDATE: 'netClaimSumValidate',
  TOTAL_RECOVERABLE_DEPRECATION_SUM_VALIDATE:
    'totalRecoverableDeprecationSumValidate',
  TOTAL_NONRECOVERABLE_DEPRECATION_SUM_VALIDATE:
    'totalNonRecoverableDeprecationSumValidate',
  NET_CLAIM_IF_DEPRECATION_IS_RECOVERED_VALIDATE:
    'netClaimIfDeprecationIsRecoveredValidate',
};

export const VALIDATION_FIELDS_TO_DATA_FIELDS = {
  //Customer
  [IMPORT_VALIDATION_FIELDS.CUSTOMER_NAME_VALIDATE]: [
    IMPORT_DETAILS_FIELDS.CUSTOMER_FIRST_NAME,
    IMPORT_DETAILS_FIELDS.CUSTOMER_LAST_NAME,
  ],
  [IMPORT_VALIDATION_FIELDS.CUSTOMER_EMAIL_VALIDATE]:
    IMPORT_DETAILS_FIELDS.CUSTOMER_EMAIL,
  [IMPORT_VALIDATION_FIELDS.CUSTOMER_PHONE_NUMBER_VALIDATE]:
    IMPORT_DETAILS_FIELDS.CUSTOMER_PHONE,
  [IMPORT_VALIDATION_FIELDS.CUSTOMER_SHIPPING_ADDRESS_VALIDATE]:
    IMPORT_DETAILS_FIELDS.CUSTOMER_SHIPPING_ADDRESS,
};

export const VALIDATION_TO_LOCALE = {
  [IMPORT_VALIDATION_FIELDS.CUSTOMER_NAME_VALIDATE]: 'contact_name',
  [IMPORT_VALIDATION_FIELDS.CUSTOMER_EMAIL_VALIDATE]: 'email',
  [IMPORT_VALIDATION_FIELDS.CUSTOMER_PHONE_NUMBER_VALIDATE]: 'phone_number',
  [IMPORT_VALIDATION_FIELDS.CUSTOMER_SHIPPING_ADDRESS_VALIDATE]:
    'shipping_address',
};

export const IMPORT_DETAILS_FIRST_TAB = 'summary';

export enum FILE_ACTIONS {
  VIEW,
  DOWNLOAD,
}

export enum IMPORT_DETAILS_ACTIONS {
  CREATE_JOB,
  SHOW_VERSION_HISTORY,
}

export const DEFAULT_EDITED_FIELD = {
  title: null,
  value: null,
  name: null,
};

export const ADJUSTERS_OPTIONS = [
  { id: 1, name: 'Claim Representative', type: 'CLAIM_REP' },
  { id: 2, name: 'Estimator', type: 'ESTIMATOR' },
];

export const ADJUSTERS_LABELS = {
  CLAIM_REP: 'Claim Representative',
  ESTIMATOR: 'Estimator',
};

// API
export const IMPORT_DETAILS_API = 'insurance-scope';
export const CUSTOMER_API = 'customer/display-name';
export const INSURANCE_CARRIER_API = 'insurance-carrier/name';
