export const groupNames: string[] = [
  'Apartment',
  'Apartment 1',
  'Apartment 2',
  'Apartment 3',
  'Area',
  'Atrium',
  'Attic',
  'Barn',
  'Basement',
  'Bathroom',
  'Bathroom (1 1/2)',
  'Bathroom (3/4)',
  'Bathroom (full)',
  'Bathroom (half)',
  'Bedroom',
  'Bedroom 1',
  'Bedroom 2',
  'Bedroom 3',
  'Breakfast Area/Room',
  'Breeze way',
  'Building',
  'Building 1',
  'Building 2',
  'Building 3',
  'Cafeteria',
  'Carport',
  'Ceiling',
  'Cellar',
  'Cleaning',
  'Closet',
  'Computer Area/Room',
  'Conference Room',
  'Crawlspace',
  'Debris Removal',
  'Deck',
  'Dining Room',
  'Display Room',
  'Doors',
  'Dwelling Roof',
  'Electrical',
  'Entry/Foyer',
  'Equipment',
  'Exam Room',
  'Exterior',
  'Exterior/General',
  'Family Room',
  'Fencing',
  'Finish Items',
  'First Floor',
  'Floor',
  'Floor Coverings',
  'Foyer/Entry',
  'Framing',
  'Front Elevation',
  'Gable',
  'Game Room',
  'Garage',
  'Gazebo',
  'Great Room',
  'Greenhouse',
  'Guest Room',
  'Hallway',
  'Heat, Vent, & Cool',
  'Hobby Area/Room',
  'Interior',
  'Kitchen',
  'Laundry Room',
  'Left Elevation',
  'Library',
  'Linen Closet',
  'Living Room',
  'Lobby',
  'Location 1',
  'Location 2',
  'Location 3',
  'Lot/Property',
  'Masonry',
  'Master Bath',
  'Master Bedroom',
  'Media Room',
  'Meeting Room',
  'Mill/Trim Work',
  'Miscellaneous',
  'Mud Room',
  'Nook',
  'Nursery',
  'Office',
  'Other',
  'Painting',
  'Pantry',
  'Patio',
  'Personal Property',
  'Play Area/Room',
  'Plumbing',
  'Pool Area',
  'Pool Enclosure',
  'Porch',
  'Rear Elevation',
  'Recreation Room',
  'Right Elevation',
  'Roof',
  'Roof Inspection',
  'Roofing',
  'Room',
  'Sales Room',
  'Sauna',
  'Screened Lanai',
  'Screened Porch',
  'Second Floor',
  'Shed',
  'Shop',
  'Show Room',
  'Siding',
  'Site Work',
  'Slab/Foundation',
  'Stairway',
  'Storage Area/Room',
  'Study',
  'Sunroom',
  'Temporary Repairs',
  'Third Floor',
  'Unit 1',
  'Unit 2',
  'Unit 3',
  'Utility Room',
  'Vanity Area/Room',
  'Walk-in Closet',
  'Wall',
  'Wallpaper/Covering',
  'Warehouse',
  'Windows',
  'Work Area/Room',
];

export const headingNames: string[] = [
  'DESCRIPTION',
  'QUANTITY',
  'AGE/LIFE COND.',
  'AGE/LIFE CONDITION',
  'AGE/LIFE',
  'COND.',
  'CONDITION',
  'CAT',
  'SEL',
  'ACT',
  'CALC',
  'QTY',
  'REMOVE',
  'REPLACE',
  'TAX',
  'O&P',
  'TAX',
  'UNIT PRICE',
  'UNIT',
  'RCV',
  'DEPREC.',
  'DEPREC. DEP %',
  'DEPRECIATION',
  'ACV',
  'UNIT',
  'DEP %',
];
